services:
  postgres:
    image: postgres:15
    container_name: trivy-postgres
    environment:
      POSTGRES_USER: trivy
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: trivydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trivy"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - trivy-network

  trivy-server:
    image: aquasec/trivy:0.69.1
    container_name: trivy-server
    command: server --listen 0.0.0.0:4954
    ports:
      - "4954:4954"
    networks:
      - trivy-network

  backend:
    build: .
    container_name: trivy-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://trivy:secret@postgres:5432/trivydb?sslmode=disable
      TRIVY_SERVER_URL: http://trivy-server:4954
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - trivy-network

  frontend:
    build: ./trivy-ui
    container_name: trivy-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:8080/api/v1
    networks:
      - trivy-network

networks:
  trivy-network:
    driver: bridge

volumes:
  pgdata: